/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <rpc/rpc.h>
#include <stdio.h>
#include "file.h"

extern __thread int errno;

readfile_res *
retrieve_file_1_svc(request *argp, struct svc_req *rqstp)
{
	static readfile_res  result;
	FILE *file;
	char data[1024];
	int bytes;
	

	file = fopen(argp->name, "rb");
	if (file == NULL) {
		result.errno = errno;
        	return (&result);
    	}

	fseek (file, argp->start, SEEK_SET);
	bytes = fread(data, 1, 1024, file);

	result.readfile_res_u.chunk.data = data;
	result.readfile_res_u.chunk.bytes = bytes;

    	result.errno = 0;
    	fclose(file);

	return &result;
}

int *
send_file_1_svc(chunksend *argp, struct svc_req *rqstp)
{
	static int  result;
	FILE *file;
	int write_bytes;

	/*
	 * insert server code here
	 */
	file = fopen(argp->name, "a");
	if (file == NULL) {
		result = errno;
		return &result;
	}

	write_bytes = fwrite(argp->data, 1, argp->bytes, file);
	fclose(file);
	result = 0;

	return &result;
}
